updates
rqrauhvmra/Tobii pull request #73
Opened 2021-06-28 21:31 UTC by viliusle

#63 - better demo
#72 fixed building on Windows, also "npm run dev-modern"
#68 - Documentation improvements (data attributes) - already on your production branch
iframe improvements

2021-06-28 21:52 UTC, midzer requested changes
First of all, big ups for your contributions! This is really massive.

Some minor style changes, sorry. Otherwise it looks really good!

This will land in a new release soon.

2021-06-28 21:52 UTC, midzer commented on demo/index.html
> +        var manual = document.querySelector('#manual');
Prefer `const` and `document.getElementById()`

2021-06-28 21:52 UTC, midzer commented on demo/index.html
> +            max-width: 1000px;
Please check the intendation (4 spaces)

2021-06-28 21:52 UTC, midzer commented on demo/index.html
> +		body{
Personally, I prefer a space behind the selector...

2021-06-28 21:52 UTC, midzer commented on src/js/index.js
> +        var video = container.getElementsByTagName('iframe')[0]
`const` here as well

2021-06-28 21:52 UTC, midzer commented on package.json
> +    "build:main": "cross-env BROWSERSLIST_ENV=main microbundle build --raw --no-sourcemap --name Tobii",
Thanks for fixing windows build!

2021-06-28 21:52 UTC, midzer commented on package.json
> +    "dev-modern": "microbundle watch --raw --format modern",
Great addition!

2021-06-28 21:52 UTC, midzer commented on demo/modern.html
> +        var manual = document.querySelector('#manual');
`const` and `document.getElementById()` again

2021-06-28 21:52 UTC, midzer commented on demo/modern.html
> +		body{
Intendation and spacing comments from `demo.html` apply here too

2021-06-28 21:52 UTC, midzer commented on demo/index.html
> +            max-width: 1000px;
(in whole file)

2021-06-29 20:02 UTC, viliusle commented
OK, but some lint rules are wrong. For example saying, that commands `font-weight: bold;` or `background: #ffffff;` or `color: #55aa22;` are incorrect, is silly... This makes code writing much slower.

Also JS without ";" and tab size with only 2 spaces is very strange for me, but I will try to adapt to these.

Can I submit issue about some lint rules?

2021-06-29 20:42 UTC, midzer approved these changes
Looks good to me!

2021-06-29 20:44 UTC, midzer commented
If you want to improve lint rules, feel free to open an issue, @viliusle

2021-06-29 20:46 UTC, merged